server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: catarina
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
springdoc:
  swagger-ui:
    path: /swagger-ui.html
