version: "3.9"

networks:
  default_net:
    name: default_net
    driver: bridge

volumes:
  database-store:
    driver: local

services:
  database:
    image: postgres:13
    container_name: database-product-api
    volumes:
      - ~/.docker-conf/postgres/data/:/var/lib/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: catarina
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: products_project_db
    networks:
      - default_net

  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq-product-api
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: catarina
      RABBITMQ_DEFAULT_PASS: 12345
    volumes:
      - database-store:/rabbitmq
    networks:
      - default_net

  redis:
    image: redis:6.2.6
    container_name: redis-product-api
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning #--requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - database-store:/redis
    networks:
      - default_net

